######################################################################
# Automatically generated by qmake (2.01a) Thu May 5 15:00:13 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += entry.h newNumber.h phonebook.h
SOURCES += entry.cpp main.cpp newNumber.cpp phonebook.cpp
