-- AVERAGE NUMBER OF WORKOUTS PER GROUP
select GROUPS.Title, avg(WiD)
from WORKOUTS, GROUPS, USERS, MEMBERS
where WORKOUTS.UiD = USERS.UiD and MEMBERS.UiD = USERS.UiD and GROUPS.GiD = MEMBERS.GiD
group by GROUPS.Title
order by avg(WiD) DESC;